# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Jackett.Jackett
PackageVersion: 0.18.984.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Jackett/Jackett/releases/download/v0.18.984/Jackett.Installer.Windows.exe
  InstallerSha256: 6DE9A1538F7CB620FB3BE9ACAE37DFC1EA816B23614812D6ED5BEB919CDD6145
ManifestType: installer
ManifestVersion: 1.0.0
