# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 95.1.31.85
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: ' '
  SilentWithProgress: ' '
UpgradeBehavior: install
Commands:
- brave
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.31.85/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 432ADACD07148A730A5C81C5218949FAD30ABB718AE1AB57EA392B75B33C8CCB
- Architecture: x86
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.31.85/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 51F780D37B2EC1A1C42DF9B4A658DF4BAF103AFC0BF3E0F03F193A4F344A427C
ManifestType: installer
ManifestVersion: 1.0.0
