# Automatically updated by the winget bot at 2022/Jan/20
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.177.5085
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: ACCEPT=YES
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2010Redist-x86
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x86
Installers:
- Architecture: x64
  InstallerUrl: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe
  InstallerSha256: CB8B4CC8CC0876CFCA8819A151D53BCBEC48924551296C495A465DD1D1529A8A
ManifestType: installer
ManifestVersion: 1.1.0
