# Automatically updated by the winget bot at 2022/Jan/15
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: LogMeIn.LastPass
PackageVersion: 4.87.0.2374
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.cloud.lastpass.com/windows_installer/LastPassInstaller.msi
  InstallerSha256: 39CD6E08F86C02BB2BE1979543FE14752523748D7F412C1CB79F2C711B30F6AE
  ProductCode: '{2426D4A3-1075-4422-8775-65538481C857}'
ManifestType: installer
ManifestVersion: 1.1.0
