# Automatically updated by the winget bot at 2022/Jan/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Nakama.Hamul
PackageVersion: 2.68.0
PackageLocale: en-US
Publisher: Nakama
PackageName: Hamul
License: Copyright © 2021 Nakama
ShortDescription: Make Real Friends, Gaming Together
ManifestType: defaultLocale
ManifestVersion: 1.0.0
