# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.3.4.0
PackageLocale: en-US
Publisher: Amazon Web Services
PublisherUrl: https://github.com/aws/aws-cli
PublisherSupportUrl: https://github.com/aws/aws-cli/issues
# PrivacyUrl: 
Author: Amazon Web Services
PackageName: AWS Command Line Interface
PackageUrl: https://aws.amazon.com/cli/
License: Apache 2.0 license
LicenseUrl: https://github.com/aws/aws-cli/blob/develop/LICENSE.txt
Copyright: Copyright 2012-2020 Amazon.com, Inc.
CopyrightUrl: https://github.com/aws/aws-cli/blob/develop/LICENSE.txt
ShortDescription: Universal Command Line Interface for Amazon Web Services
Description: The AWS CLI is an open source tool built on top of the AWS SDK for Python (Boto) that provides commands for interacting with AWS services. With minimal configuration, you can start using all of the functionality provided by the AWS Management Console from your favorite terminal program.
Tags:
- awscli
- aws
- cli
- cloud
- web
- services
- s3
- foss
- open-source
ManifestType: defaultLocale
ManifestVersion: 1.0.0
