# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: TTKN.CAJViewer
PackageVersion: 7.3.1
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /C:"msiexec /i ""CAJViewer 7.3.msi"" /quiet /norestart
  SilentWithProgress: /C:"msiexec /i ""CAJViewer 7.3.msi"" /passive /norestart
  Log: /log ""<LOGPATH>"""
InstallerSuccessCodes:
- 3010
UpgradeBehavior: uninstallPrevious
FileExtensions:
- caa
- caj
- kdh
- nh
- pdf
- teb
Installers:
- Architecture: x86
  InstallerUrl: https://download.cnki.net/CAJViewer%207.3.141.self.exe
  InstallerSha256: 9DB367042194AF80C40E2E618F0E420528DE3C5098315B4BA1DAF9855F3747A0
  ProductCode: '{38CE8FAD-2E31-4CA8-B671-1BA7A8A54B28}'
ManifestType: installer
ManifestVersion: 1.1.0
