# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: SoftDeluxe.FreeDownloadManager
PackageVersion: 6.15.3.4236
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- http
- https
- torrent
FileExtensions:
- fdd
- fds
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://dn3.freedownloadmanager.org/6/latest/fdm_x64_setup.exe
  InstallerSha256: 0A277852147A058145F2E2DA10E4172E35EBACAA612BCFD77F02A7E0FFF4C6C8
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  Scope: user
  InstallerUrl: https://dn3.freedownloadmanager.org/6/latest/fdm_x64_setup.exe
  InstallerSha256: 0A277852147A058145F2E2DA10E4172E35EBACAA612BCFD77F02A7E0FFF4C6C8
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://dn3.freedownloadmanager.org/6/latest/fdm_x86_setup.exe
  InstallerSha256: 127FD2BF448462C38FCC4A966F6B96C10D73EACCFB873C5874778B520D7E26D0
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x86
  Scope: user
  InstallerUrl: https://dn3.freedownloadmanager.org/6/latest/fdm_x86_setup.exe
  InstallerSha256: 127FD2BF448462C38FCC4A966F6B96C10D73EACCFB873C5874778B520D7E26D0
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.0.0

