# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: MYKIInc.MYKIDesktopApp
PackageVersion: 1.4.6
PackageLocale: en-US
Publisher: MYKI Inc.
PackageName: MYKI Desktop App
License: Copyright © 2021 MYKI Inc.
ShortDescription: MYKI Desktop App
ManifestType: defaultLocale
ManifestVersion: 1.0.0

