# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: MYKIInc.MYKIDesktopApp
PackageVersion: 1.4.6
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://static.myki.com/releases/da/MYKI-latest.exe
  InstallerSha256: 9769431D542FD3BF66BE48A58049ED2E4B06D79AD6584AA16696990D636C56C2
ManifestType: installer
ManifestVersion: 1.0.0

