# Automatically updated by the winget bot at 2022/Jan/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Todesk.Todesk
PackageVersion: 4.2.0.01191912
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- todesk
Installers:
- Architecture: x86
  InstallerUrl: https://dl.todesk.com/windows/ToDesk_Setup.exe
  InstallerSha256: 2E708CE9B7D78A23A3209264785A1186EE8979B6FB8964EC43FA1DFB1D27E7A3
  ProductCode: ToDesk
ManifestType: installer
ManifestVersion: 1.1.0
