# Created with YamlCreate.ps1 v2.0.0 $debug=NVS1.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: OpenMedia.4KVideoToMP3
PackageVersion: 3.0.1.936
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
