# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: WireGuard.WireGuard
PackageVersion: 0.4.11
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /NORESTART DO_NOT_LAUNCH=1
Commands:
- wireguard
Protocols:
- udp
FileExtensions:
- zip
- conf
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://download.wireguard.com/windows-client/wireguard-amd64-0.4.11.msi
  InstallerSha256: 647668DD264BE9A46780686466442C215056633F3AEB802041E06E5481FE048F
  UpgradeBehavior: install
  ProductCode: "{AF987235-A3E0-4B6B-8348-105F711FC812}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://download.wireguard.com/windows-client/wireguard-x86-0.4.11.msi
  InstallerSha256: A7A4FF4CD19B06FA42A24F597F8275886316B73B094157AA4459884FA84C40D5
  UpgradeBehavior: install
  ProductCode: "{80307147-E425-430D-8A2F-C66EE60A1656}"
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://download.wireguard.com/windows-client/wireguard-arm64-0.4.11.msi
  InstallerSha256: 2AB25B8507AACA45086E7B65773775B5D43472536C88626696B20753B2F96F5B
  UpgradeBehavior: install
  ProductCode: "{FD794621-D7ED-4206-A356-5446A6DD64B6}"
- InstallerLocale: en-US
  Architecture: arm
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://download.wireguard.com/windows-client/wireguard-arm-0.4.11.msi
  InstallerSha256: ED217FE5FCC6C16CF4D71EC70B341A350E9266A8B1124CB661C453C0DF513B7B
  UpgradeBehavior: install
  ProductCode: "{6418A2F1-CA3C-46C2-B82A-6068FBFA7B80}"
ManifestType: installer
ManifestVersion: 1.0.0

