# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: ZeroTier.ZeroTierOne
PackageVersion: 1.8.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /quiet
UpgradeBehavior: install
Installers:
- Architecture: neutral
  InstallerUrl: https://download.zerotier.com/RELEASES/1.8.3/dist/ZeroTierOne.msi
  InstallerSha256: 656891485FF9D132616323EA5812EC4EE63440C6F10427E3B9214C648F682D0F
  ProductCode: '{1A2C3363-43B4-40BA-8614-027C94856419}'
ManifestType: installer
ManifestVersion: 1.0.0

