# Created using YamlCreate.ps1 v1.1.7
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: easymodo.qimgv
PackageVersion: 1.0.2
MinimumOSVersion: 10.0.0.0
FileExtensions:
- apng
- avif
- bmp
- gif
- jfif
- jpe
- jpeg
- jpg
- jxl
- mp4
- png
- webm
- webp
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/easymodo/qimgv/releases/download/v1.0.2/qimgv-x64_1.0.2-video.exe
  InstallerSha256: F351C3D44A62DC1287A8B2A46647C6FBFE38AC94000E9FA454652416D1B60843
  ProductCode: '{5E9AB208-B553-414A-828D-945F642CDBE1}_is1'
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

