# Created using YamlCreate.ps1 v1.1.7
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json

PackageIdentifier: easymodo.qimgv
PackageVersion: 1.0.2
PackageLocale: zh-CN
Publisher: easymodo
PublisherUrl: https://github.com/easymodo
PublisherSupportUrl: https://github.com/easymodo/qimgv/issues
#PrivacyUrl: 
Author: easymodo
PackageName: qimgv
PackageUrl: https://github.com/easymodo/qimgv
License: GPL-3.0
LicenseUrl: https://raw.githubusercontent.com/easymodo/qimgv/master/LICENSE
#Copyright: 
#CopyrightUrl: 
ShortDescription: Qt5 图像查看器，可选视频支持
#Description: 
Tags:
- 图像
- 图片
- 照片
- 查看器
- 视频
- 播放器
- bmp
- gif
- jpg
- png
- webp
- qimgv
- easymodo
ManifestType: locale
ManifestVersion: 1.0.0

