# Automatically updated by the winget bot at 2022/Jan/15
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: HiBitSoftware.HiBitUninstaller
PackageVersion: 2.7.40.100
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://www.hibitsoft.ir/HiBitUninstaller/HiBitUninstaller-setup.exe
  InstallerSha256: 3944224B62A5C4D61D973611739EA9D04116B9BDED758A92457EA1607288F9D7
ManifestType: installer
ManifestVersion: 1.1.0
