# Automatically updated by the winget bot at 2021/Nov/02
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Icons8.Lunacy
PackageVersion: 8.0.4.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://lun-static.s3.us-west-000.backblazeb2.com/setup/LunacySetup.exe
  InstallerSha256: BEB06EC0BD8460702DDD48C1423B9F056B6E69AFBD75B9D1FE8DE313B8233034
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://lun-static.s3.us-west-000.backblazeb2.com/setup/LunacySetup_x86.exe
  InstallerSha256: 9A2F6C61A88437ABF9F4B354A8431BF1ECA834245AB13CF6FDBCE836FC7D89A5
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
