# Created with YamlCreate.ps1 v2.0.0 $debug=NVS1.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: OpenMedia.4KSlideshowMaker
PackageVersion: 2.0.1.1055
PackageLocale: en-US
Publisher: OpenMedia LLC
PublisherUrl: https://www.4kdownload.com
PublisherSupportUrl: https://www.4kdownload.com/help
PrivacyUrl: https://www.4kdownload.com/privacy
Author: OpenMedia LLC
PackageName: 4K Slideshow Maker
PackageUrl: https://www.4kdownload.com/products/product-slideshowmaker
License: Freeware
LicenseUrl: https://www.4kdownload.com/agreement/freeware
Copyright: © 2021 Open Media
CopyrightUrl: https://www.4kdownload.com/agreement/freeware
ShortDescription: Create impressive slideshows, save your memories
# Description: 
Moniker: 4kslideshowmaker
Tags:
- slideshow-maker
- slideshows
- images
- videos
ManifestType: defaultLocale
ManifestVersion: 1.0.0
