# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json
PackageIdentifier: ImageMagick.ImageMagick
PackageVersion: 7.1.0.19
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- bmp
- eps
- gif
- jpg
- mif
- miff
- png
- svg
- tif
- tiff
- wmf
Installers:
- Architecture: x64
  InstallerUrl: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-19-Q16-HDRI-x64-dll.exe
  InstallerSha256: 40DE58930E0F41E3F71BEBE12BEFC326FADE7D953B552936EA4A88A1267CF451
  ProductCode: ImageMagick 7.1.0 Q16-HDRI (64-bit)_is1
- Architecture: x86
  InstallerUrl: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-19-Q16-HDRI-x86-dll.exe
  InstallerSha256: 9BEE2BAABDF02AE5CA3CFC9996D667CEA2FE792DC4EDFE9286B1F0803D5831CD
  ProductCode: ImageMagick 7.1.0 Q16-HDRI (32-bit)_is1
ManifestType: installer
ManifestVersion: 1.1.0

