# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: PTRTECH.UVtools
PackageVersion: 2.27.2
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/sn4k3/UVtools/releases/download/v2.27.2/UVtools_win-x64_v2.27.2.msi
  InstallerSha256: 42ED8E00C4DB15FA7C607879E7F18636F3C3D72ECCB62EE2E430A9407BDB64F3
  ProductCode: '{83995BA3-314E-4C68-A6F7-2ADDBE47FAA2}'
ManifestType: installer
ManifestVersion: 1.0.0

