# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: OpenJS.NodeJS
PackageVersion: 16.11.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v16.11.0/node-v16.11.0-x64.msi
  InstallerSha256: EC495FAFFE733E998FD78EFA7C6C8DE047690BAD2A6CD4CA088FBED72FF68358
  UpgradeBehavior: install
  ProductCode: "{CA013CB0-B2C4-4404-B511-F65BEDAF2D93}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v16.11.0/node-v16.11.0-x86.msi
  InstallerSha256: 8BE850C1384B5E96437FF2B884CB5ADD60BD44960863406DFDDFBC08DC9C96A9
  UpgradeBehavior: install
  ProductCode: "{2E545055-F421-464F-9C15-26F0146B0723}"
ManifestType: installer
ManifestVersion: 1.0.0

