# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Velocidex.Velociraptor
PackageVersion: 0.62.2
PackageLocale: en-US
Publisher: Velocidex
PublisherUrl: https://www.velocidex.com/
PublisherSupportUrl: https://groups.google.com/forum/#!forum/velociraptor-discuss
# PrivacyUrl: 
Author: Velocidex
PackageName: Velociraptor
PackageUrl: https://docs.velociraptor.app/
License: GNU Affero General Public License, Version 3
LicenseUrl: https://raw.githubusercontent.com/Velocidex/velociraptor/master/LICENSE
# Copyright: 
CopyrightUrl: https://raw.githubusercontent.com/Velocidex/velociraptor/master/LICENSE
ShortDescription: Velociraptor is a tool for collecting host based state information using The Velociraptor Query Language (VQL) queries.
# Description: 
# Tags: 
ManifestType: defaultLocale
ManifestVersion: 1.0.0
