# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.2.46.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- aws
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.2.46.msi
  InstallerSha256: 8FDBCD3767AADC58E0A97D883AE239C55DFDD1F5DFDEF27300BDCF919EBC3CBE
  UpgradeBehavior: install
  ProductCode: "{B1D5534C-0821-4FA9-857B-2971BA574052}"
ManifestType: installer
ManifestVersion: 1.0.0

