# Automatically updated by the winget bot at 2022/Jan/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Postman.Postman.Canary
PackageVersion: 9.8.3-canary02
MinimumOSVersion: 10.0.0.0
InstallerType: exe
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
UpgradeBehavior: install
Installers:
- Architecture: neutral
  InstallerUrl: https://dl.pstmn.io/download/channel/canary/windows_64
  InstallerSha256: 7715D18DAA62B5CC2BD923B4F4A860894A6F3DB86F302BC4BE15D94B5C41E93D
  ProductCode: 'PostmanCanary'
ManifestType: installer
ManifestVersion: 1.1.0
