# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Amazon.Corretto.8
PackageVersion: 1.8.0.312
PackageName: Amazon Corretto 8
Publisher: Amazon
PackageUrl: https://docs.aws.amazon.com/corretto/index.html
License: GPL 2 with Classpath Exception
LicenseUrl: https://github.com/corretto/corretto-8/blob/develop/LICENSE
ShortDescription: No-cost, multiplatform, production-ready distribution of the Open Java Development Kit (OpenJDK).
Installers:
- Architecture: x64
  InstallerUrl: https://corretto.aws/downloads/resources/8.312.07.1/amazon-corretto-8.312.07.1-windows-x64-jdk.msi
  InstallerType: msi
  InstallerSha256: AD70574432DDB0EEB4AE9A117C92357600029CA5621A870409B33F6A8B9BBBCA
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /passive
  ProductCode: "{E5F235CB-B351-4AD1-8B64-C073F67733D9}"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

