# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Amazon.SAM-CLI
PackageVersion: 1.34.1
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{11A619E1-956C-4431-A038-073E6300CC4C}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/aws/aws-sam-cli/releases/download/v1.34.1/AWS_SAM_CLI_64_PY3.msi
  InstallerSha256: 4F4EE43FD0F8FEEEAE90D7B9173FB5BD8DE276A9E2865EF0F8382841503672C8
ManifestType: installer
ManifestVersion: 1.0.0
