# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Microsoft.WindowsPCHealthCheck
PackageVersion: 3.1.2109.29003
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

