# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: 7zip.7zip
PackageVersion: "21.05"
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- 7z
FileExtensions:
- 7z
- AR
- ARJ
- BZIP2
- CAB
- CHM
- CPIO
- CramFS
- DMG
- EXT
- FAT
- GPT
- GZIP
- HFS
- IHEX
- ISO
- LZH
- LZMA
- MBR
- MSI
- NSIS
- NTFS
- QCOW2
- RAR
- RPM
- SquashFS
- TAR
- UDF
- UEFI
- VDI
- VHD
- VMDK
- WIM
- XAR
- XZ
- Z
- ZIP
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://www.7-zip.org/a/7z2105-x64.exe
  InstallerSha256: A7CE7801563FB7D8A9018C54560B675F21B778AFD01537FFD4A1B7AF4B3D0043
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://www.7-zip.org/a/7z2105.exe
  InstallerSha256: B7F91D9F839709316E6B9D61F3D156511A09B371C66EEAFCC4C827AD52FCCED4
- Architecture: arm64
  InstallerType: nullsoft
  InstallerUrl: https://www.7-zip.org/a/7z2105-arm64.exe
  InstallerSha256: 4756A23E9B32279F10E74DEA0DB2E96BF6DDA7347089BE3728AB082A7F3E8DA0
ManifestType: installer
ManifestVersion: 1.1.0
