# Created using YamlCreate.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: tibbo.ioninja
PackageVersion: 5.0.4
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://tibbo.com/downloads/archive/ioninja/ioninja-5.0.4/ioninja-5.0.4-windows-amd64-core.msi
  InstallerSha256: 0CE0D78E54C336BAEB77D0E8E56C773F3E6B1643C13FB03F077C6E157D0E217B
  ProductCode: '{D12DEA73-440C-41C7-8F28-76569F2C0694}'
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://tibbo.com/downloads/archive/ioninja/ioninja-5.0.4/ioninja-5.0.4-windows-x86-core.msi
  InstallerSha256: 414C2A3155DFF716D21046824FE9EF6B3075AA3F9F832FA3CC02082E334650F0
  ProductCode: '{1042F330-DF57-4DCE-8BC3-EB8059985505}'
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
