# Automatically updated by the winget bot at 2022/Jan/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Wondershare.DemoCreator
PackageVersion: 5.5.0.29
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download.wondershare.com/cbs_down/democreator_full7743.exe
  InstallerSha256: B7E2B76E78D6049D0A972384C5337594C72803A19839ACB7F83D5A1FA3FCA95B
ManifestType: installer
ManifestVersion: 1.0.0
