# Automatically updated by the winget bot at 2022/Jan/05
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BitSum.ProcessLasso
PackageVersion: 10.4.2.16
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://dl.bitsum.com/files/processlassosetup64.exe
  InstallerSha256: F0A40118383802A5EFB6E2E4CFFB9CE52E87A76BAA896C0DE5C5CF7E562887AB
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
