# Created with YamlCreate.ps1 v2.0.2 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: QL-Win.QuickLook
PackageVersion: 3.7.1.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/QL-Win/QuickLook/releases/download/3.7.1/QuickLook-3.7.1.msi
  InstallerSha256: 16641DB14617C403100AD890CCF1706082A9F08B38812D566E4D4CFCD627EC59
ManifestType: installer
ManifestVersion: 1.1.0
