# Automatically updated by the winget bot at 2021/Nov/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: SigmaSolutions.Mongomix
PackageVersion: 1.8.7.0
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://mongomix.sigma-solutions.fr/release/mongomix.msi
  InstallerSha256: C667C379F56AC37B8586C7807F69D6D9139C6161E43DA19C9A11356F5008798D
  ProductCode: '{A74E58C7-3ACA-41ED-B17A-1FD48DA7CF78}'
ManifestType: installer
ManifestVersion: 1.0.0
