# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Streamlabs.StreamlabsOBS
PackageVersion: 1.5.1
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://slobs-cdn.streamlabs.com/Streamlabs+OBS+Setup+1.5.1.exe
  InstallerSha256: A396834A4A5C0F08C25E9EAA4F3CEDAA4DB96BD37F62ACF481E2DCA72BC48804
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

