# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: blueedge.win11react
PackageVersion: 0.1.2
PackageLocale: en-US
Publisher: com.blueedgetechno.win11react
PackageName: Win11inReact
License: CC0-1.0 License
ShortDescription: A recreation of Windows 11 in React
ManifestType: defaultLocale
ManifestVersion: 1.0.0

