# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Cisco.CiscoWebexMeetings
PackageVersion: 41.10.3.19
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://akamaicdn.webex.com/client/WBXclient-41.10.3-19/webexapp.msi
  InstallerSha256: CB3E63FC628BFCF61C2C7EB4752E15287E2009D2E4A446DC1CDE15DAB2008CEB
  UpgradeBehavior: install
  ProductCode: "{698FED1D-185D-E036-EF8C-D96F59C29C5C}"
ManifestType: installer
ManifestVersion: 1.0.0

