# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.5-1-22000-282
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: MariaDB.Server
PackageVersion: 10.7.1.0
PackageLocale: en-US
Publisher: MariaDB Corporation Ab
PublisherUrl: https://mariadb.org
# PublisherSupportUrl: 
PrivacyUrl: https://mariadb.org/privacy-policy/
Author: MariaDB Corporation Ab
PackageName: MariaDB
PackageUrl: https://mariadb.org
License: GPL 2.0 only
LicenseUrl: https://mariadb.com/kb/en/mariadb-license/
# Copyright: 
# CopyrightUrl: 
ShortDescription: Community developed fork of MySQL server.
# Description: 
Moniker: mariadb
Tags:
- rdbms
- sql
- database
- mysql
ManifestType: defaultLocale
ManifestVersion: 1.0.0
