name: 'Bug report'
description: Report errors or unexpected behavior
title: "[Bug]: "
labels: ["Issue-Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)
  - type: textarea
    attributes:
      label: Brief description of your issue
      placeholder: Briefly describe your issue here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: How to reproduce the issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: What is currently happening?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        [winget --info]
        Windows Package Manager version
        Windows: Windows.Desktop version
        Package: Microsoft.DesktopAppInstaller version
        Any other software?
      render: shell
    validations:
      required: true
