# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.LabPlot
PackageVersion: 2.8.2-1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- cws
- ipynb
- lml
- opj
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Labplot_Release_win64/644/artifact/labplot-2.8.2-1-644-windows-msvc2019_64-cl.exe
  InstallerSha256: A4AB43D670BD1A0409144C679D2D523815DBFFE8CB317AB76174C4AAFF8F08C1
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Labplot_Release_win64/644/artifact/labplot-2.8.2-1-644-windows-msvc2019_64-cl.exe
  InstallerSha256: A4AB43D670BD1A0409144C679D2D523815DBFFE8CB317AB76174C4AAFF8F08C1
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0
