# Automatically updated by the winget bot at 2022/Jan/18
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: BitSum.ProcessLasso.Beta
PackageVersion: 10.4.3.9
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
  InstallerSha256: D16EACF207E9703491BA52297D504049BCA0B4ADF49E6BFEAA1E2A662AEB0319
ManifestType: installer
ManifestVersion: 1.1.0
