# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: OpenJS.NodeJS
PackageVersion: 17.0.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v17.0.0/node-v17.0.0-x64.msi
  InstallerSha256: 746042B936FBD3C67988FCCE2B4BFAA0516765B26A02500376427E907EE929F2
  UpgradeBehavior: install
  ProductCode: "{339E3BD8-2594-4D39-8865-A7B77035484F}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v17.0.0/node-v17.0.0-x86.msi
  InstallerSha256: C0A3B338ED0519DB2BB14890F27F443DCF620AB6D11EF3CE17B2242074BEE5C6
  UpgradeBehavior: install
  ProductCode: "{5360C47A-33A0-4DEA-B946-67A3C00AA635}"
ManifestType: installer
ManifestVersion: 1.0.0

