# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Shabinder.SpotiFlyer
PackageVersion: 3.5.0
PackageLocale: en-US
Publisher: Shabinder
PublisherUrl: https://github.com/Shabinder/SpotiFlyer
# PublisherSupportUrl: 
# PrivacyUrl: 
Author: Shabinder
PackageName: SpotiFlyer
PackageUrl: https://github.com/Shabinder/SpotiFlyer
License: GPL-3.0
LicenseUrl: https://raw.githubusercontent.com/Shabinder/SpotiFlyer/main/LICENSE
# Copyright: 
# CopyrightUrl: 
ShortDescription: SpotiFlyer is a music downloader that supports Spotify, Gaana, Youtube Music, Jio Saavn.
# Description: 
Moniker: spotiflyer
Tags:
- youtube-downloader
- spotify-downloader
- music-downloader
- song-downloader
ManifestType: defaultLocale
ManifestVersion: 1.0.0
