# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: DuongDieuPhap.ImageGlass
PackageVersion: 8.4.1.22
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- ai
- avif
- b64
- bmp
- bvif
- cur
- cut
- dib
- emf
- eps
- exif
- exr
- gif
- hdr
- heic
- heif
- ico
- jfif
- jp2
- jpe
- jpeg
- jpg
- mpg
- pbm
- pcx
- pgm
- png
- ppm
- psd
- raw
- rga
- svg
- tif
- tiff
- webp
- wmf
- wpg
- xbm
- xpm
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/d2phap/ImageGlass/releases/download/8.4.1.22/ImageGlass_8.4.1.22_x64.msi
  InstallerSha256: E03BE98A5560CF0D1BAC11859D2384E19C9F0D3C0AAC9FA831DE36E946C1F45E
  ProductCode: '{7BC18B4D-18B0-4111-8DB6-37ADA303722B}'
- Architecture: x86
  InstallerUrl: https://github.com/d2phap/ImageGlass/releases/download/8.4.1.22/ImageGlass_8.4.1.22_x86.msi
  InstallerSha256: 9BAE3543F8C7E5173DA3F5E6B22D03AA968A47F35BC375FC859646C208780539
  ProductCode: '{4510DC5E-9A94-4E31-A9AE-9B6DA1F5B779}'
ManifestType: installer
ManifestVersion: 1.1.0
