# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: GrafanaLabs.GrafanaEnterprise
PackageVersion: 8.2.1.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.grafana.com/enterprise/release/grafana-enterprise-8.2.1.windows-amd64.msi
  InstallerSha256: 41BAD1A980BE329FAF191E6FFC791763F2CAD353F3F1CEDB87DAF21A8C51938B
  UpgradeBehavior: install
  ProductCode: "{25D2B465-F5F6-4486-980B-DB93AA974C1F}"
ManifestType: installer
ManifestVersion: 1.0.0

