PackageIdentifier: MarekJasinski.FreeCommanderXE
PackageVersion: 20.0.810
PackageName: FreeCommander XE
Publisher: Marek Jasinski - www.FreeCommander.com
License: Copyright (c) 2004-2020 Marek Jasinski
LicenseUrl: https://freecommander.com/en/license/
Moniker: freecommander
Tags:
- commander
- file-manager
- explorer
- files
ShortDescription: FreeCommander is an easy-to-use alternative to the standard windows file manager. The program helps you with daily work in Windows.
PackageUrl: https://freecommander.com
Installers:
- Architecture: x86
  InstallerUrl: https://freecommander.com/downloads/FreeCommanderXE-32-public_810a.msi
  InstallerSha256: B5A15F5FB027469DC10D2E3F2DEE9EDF2F0069BEFD7880D75DCCB4E613E00042
  ProductCode: "{72D02D56-AA28-4174-8B29-D3FD17F8946D}"
  Scope: machine
  InstallerType: msi
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
