# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: VB-Audio.Voicemeeter
PackageVersion: 1.0.8.1
Platform:
- Windows.Desktop
MinimumOSVersion: 5.1.2600.2180
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silentWithProgress
InstallerSwitches:
  Silent: -install
  SilentWithProgress: -install
  Upgrade: -upgrade
UpgradeBehavior: install
Protocols:
- vban
Installers:
- Architecture: x64
  InstallerUrl: https://download.vb-audio.com/Download_CABLE/VoicemeeterSetup.exe
  InstallerSha256: C4AA7D0E404B6D89F46FEC8145D323830F8E8B56E0597C3B796B177A7A5511C4
- Architecture: x86
  InstallerUrl: https://download.vb-audio.com/Download_CABLE/VoicemeeterSetup.exe
  InstallerSha256: C4AA7D0E404B6D89F46FEC8145D323830F8E8B56E0597C3B796B177A7A5511C4
ManifestType: installer
ManifestVersion: 1.0.0
