# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Jelmerro.Vieb
PackageVersion: 7.0.0
PackageLocale: en-US
Publisher: Jelmer van Arnhem
PublisherUrl: https://jelmerro.nl/
PublisherSupportUrl: https://github.com/Jelmerro/Vieb/issues/
# PrivacyUrl: 
Author: Jelmer van Arnhem
PackageName: Vieb
PackageUrl: https://vieb.dev/
License: GPL-3.0
LicenseUrl: https://raw.githubusercontent.com/Jelmerro/Vieb/master/LICENSE
Copyright: Copyright (C) 2020-2021 Jelmer van Arnhem
CopyrightUrl: https://raw.githubusercontent.com/Jelmerro/Vieb/master/LICENSE
ShortDescription: Vim Inspired Electron Browser
# Description: 
# Moniker: 
Tags:
- browser
- electron
- vim
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
