# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: McServ.McServ
PackageVersion: 0.1.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/DRSchlaubi/mcserv/releases/download/v0.1.1/mcserv-0.1.1.msi
  InstallerSha256: 903269FAE8DD397D1BE0C659CC60E48FBAEEEEAF24ABEF64F6512E3AE6838223
  ProductCode: '{F533613B-2F56-4E49-A8CC-EFD1BF1DD985}'
ManifestType: installer
ManifestVersion: 1.1.0

