# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Cisco.CiscoWebexMeetings
PackageVersion: 41.11.2.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://akamaicdn.webex.com/client/WBXclient-41.11.2-2/webexapp.msi
  InstallerSha256: 3A2E4C72EEC8CE69D722CD1FE1D90E4A7EF592A3E5CCC29C536E525D8B336A89
  UpgradeBehavior: install
  ProductCode: "{8C6C1C34-324D-F249-4F96-9D068C342ABF}"
ManifestType: installer
ManifestVersion: 1.0.0

