# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Jackett.Jackett
PackageVersion: 0.18.1022.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Jackett/Jackett/releases/download/v0.18.1022/Jackett.Installer.Windows.exe
  InstallerSha256: 60488B2CD1515BE82E37E6D498C975F07F30F83698C82DD9BF92839F4225A41D
ManifestType: installer
ManifestVersion: 1.0.0
