# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Anydo.Anydo
PackageVersion: 4.2.158
PackageLocale: en-US
Publisher: Any.do
PublisherUrl: https://www.any.do
PublisherSupportUrl: https://support.any.do
PrivacyUrl: https://www.any.do/legal/privacy-policy
Author: Any.do
PackageName: Any.do
PackageUrl: https://www.any.do
License: Proprietary
LicenseUrl: https://www.any.do/legal/app-license-agreement
Copyright: Copyright (c) Any.do 2021
CopyrightUrl: https://www.any.do/legal/app-license-agreement
ShortDescription: Organize your tasks, lists and reminders in Any.do app.
# Description: 
Moniker: any.do
# Tags: 
ManifestType: defaultLocale
ManifestVersion: 1.0.0
