# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Anydo.Anydo
PackageVersion: 4.2.158
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://electron-app.any.do/_windows/Any.do.exe
  InstallerSha256: 95FF493AF926DAFFDF2AD32AD613A53636B0D5799C17DBEA636406EBFA268929
ManifestType: installer
ManifestVersion: 1.0.0
