# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: OpenJS.NodeJS
PackageVersion: 16.12.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v16.12.0/node-v16.12.0-x64.msi
  InstallerSha256: D269299D5FEB29BC9D5713E9B87F0154FF857BBE6510C76A553568A1BC22BADC
  UpgradeBehavior: install
  ProductCode: "{0E43E114-8AEE-48C2-AE89-CBD081C47209}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v16.12.0/node-v16.12.0-x86.msi
  InstallerSha256: ADC0B407F5B856FAD4E36AC7B22DEF93CF01B6F7576404DA7C5B6A3992A82236
  UpgradeBehavior: install
  ProductCode: "{E80B2CA6-0B88-4439-95C3-430258CE33CA}"
ManifestType: installer
ManifestVersion: 1.0.0

