# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BlenderFoundation.Blender
PackageVersion: 2.93.5
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
FileExtensions:
- obj
- fbx
- 3ds
- ply
- stl
- gltf
- glb
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://download.blender.org/release/Blender2.93/blender-2.93.5-windows-x64.msi
  InstallerSha256: EB8FD2B48D6D84530A5A988BF11B4751A9F4D206D31A6BB71A1052F2AE9D971E
  UpgradeBehavior: uninstallPrevious
  ProductCode: "{3033FBAD-BA86-469B-8C6F-ECD41334BD4D}"
ManifestType: installer
ManifestVersion: 1.0.0

