# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: VB-Audio.Voicemeeter.Banana
PackageVersion: 2.0.6.1
Platform:
- Windows.Desktop
MinimumOSVersion: 5.1.5600.2180
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -install
  SilentWithProgress: -install
  Upgrade: -upgrade
UpgradeBehavior: install
Protocols:
- vban
Installers:
- Architecture: x64
  InstallerUrl: https://download.vb-audio.com/Download_CABLE/VoicemeeterProSetup.exe
  InstallerSha256: 8B2BA7CA09E0BF23A7C374CC65CF1F18D64E5C7211E68B1E9E6525D97EDBA92A
- Architecture: x86
  InstallerUrl: https://download.vb-audio.com/Download_CABLE/VoicemeeterProSetup.exe
  InstallerSha256: 8B2BA7CA09E0BF23A7C374CC65CF1F18D64E5C7211E68B1E9E6525D97EDBA92A
ManifestType: installer
ManifestVersion: 1.0.0
