# Automatically updated by the winget bot at 2022/Jan/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: UnityTechnologies.UnityHub
PackageVersion: 3.0.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe
  InstallerSha256: 3EDF37D1F89A8EF7E9457F4A70EFC99BB12F86E37102FF6EEF3169BC14F27184
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
