# Automatically updated by the winget bot at 2021/Nov/25
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: WorksMobile.NAVERWORKS
PackageVersion: 3.2.3.21
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Platform:
  - Windows.Desktop
  InstallerLocale: ko-KR
  Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://download.worksmobile.com/k/wminst/r/naverworks/deploy_pcmsgapp_win32_exe
  InstallerSha256: AD9CE4095E380D2F7B97AEF5F31466B2477D0025A83418AB8126BAA53DF6C10D
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
