# Automatically updated by the winget bot at 2022/Jan/18
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: RARLab.WinRAR.Beta
PackageVersion: 6.10.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Commands:
- winrar
FileExtensions:
- ‘001’
- 7z
- arj
- bz2
- cab
- gz
- iso
- jar
- lz
- lzh
- rar
- tar
- uue
- xz
- z
- zip
- zipx
Installers:
- Architecture: x64
  InstallerUrl: https://www.rarlab.com/rar/winrar-x64-610b3.exe
  InstallerSha256: 91E6BA95863E46A44AEC9FF9B882EF6494108B626E61B5326EA9D5FB63607111
- Architecture: x86
  InstallerUrl: https://www.rarlab.com/rar/winrar-x32-610b3.exe
  InstallerSha256: 159B02B7B470EE67501656465FFA53BAC7CB02ABA997C1D53550B9F81DAF114F
ManifestType: installer
ManifestVersion: 1.1.0
