# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.3.3.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- aws
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.3.3.msi
  InstallerSha256: C2CB707AC5E8FE11A1C2EA984DDF948720BDAE34FEA306D06FDA1AB62B0DDE65
  ProductCode: "{751D624B-C16E-4EBE-A085-74B49F683DA3}"
ManifestType: installer
ManifestVersion: 1.0.0

