# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.40.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.40.0/nu_0_40_0_windows.msi
  InstallerSha256: 116EDB47155222BAE171A1BDDD590927C8FB61680823719168E8E8E0D56545A9
  ProductCode: '{B0009606-2FB1-48B2-850D-97A7A433334B}'
ManifestType: installer
ManifestVersion: 1.0.0

