# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome.Dev
PackageVersion: 98.0.4758.9
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise64.msi
  InstallerSha256: 16CBFE270D7C0E9B56DE5ACBB98FACC9A93CD35F091006014FFC14D12A951224
  ProductCode: '{D65BB9BE-3A62-3421-AD74-1F682CAC344E}'
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise.msi
  InstallerSha256: 23BC68B394499EC62C214296522E863F41FC3E7AC22EFAB83467323A78B394CD
  ProductCode: '{72131B72-719B-388F-A307-A36CD1D17EDB}'
ManifestType: installer
ManifestVersion: 1.1.0
