# Automatically updated by the winget bot at 2022/Jan/06
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Todesk.Todesk
PackageVersion: 4.1.3.01051200
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- todesk
Installers:
- Architecture: x86
  InstallerUrl: https://dl.todesk.com/windows/ToDesk_Setup.exe
  InstallerSha256: 233CD5092347DF3B4E8B035AD02BA067670E87F6C1E982897A1DC9834E2F307A
  ProductCode: ToDesk
ManifestType: installer
ManifestVersion: 1.1.0
