# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: DoltHub.Dolt
PackageVersion: 0.30.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{8C709A9E-987C-4D9F-9878-942FB4F4EEF0}'
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/dolthub/dolt/releases/download/v0.30.0/dolt-windows-amd64.msi
  InstallerSha256: 53BD968A41719544E96343D9DDBA3BB253C18E05C11DE5379C13A1F8A3751552
  ProductCode: '{C4A0E5B6-793D-417E-8510-04FD62CE82C1}'
ManifestType: installer
ManifestVersion: 1.0.0

