# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json
PackageIdentifier: Amazon.Corretto.11
PackageVersion: 11.0.13.8
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

