# Automatically updated by the winget bot at 2021/Dec/25
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: VMware.IntelligentHub
PackageVersion: 21.7.8.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{3D2DB516-DFBD-4E7E-2F1B-E64A950A332D}'
Installers:
- Architecture: x86
  InstallerUrl: https://packages.vmware.com/wsone/AirwatchAgent.msi
  InstallerSha256: 0B605377B55533588DB80780B9B7B31BDF2A3FA26D5BED628545CFF9E991637E
ManifestType: installer
ManifestVersion: 1.0.0
