# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.5-1-19041-1237
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Ability.AbilityOffice.10.Standard
PackageVersion: 10.0.3
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
ProductCode: '{8CCC33AC-4169-4EAC-98AC-C9EA7A06BAEB}'
Installers:
- Architecture: x86
  InstallerUrl: https://ability.com/ab10/msi/AbilitySTD10_EN.msi
  InstallerSha256: A50D618675FAF739AA6DE8E3E139AFA9666C4FEF01C7B0A2C56D305B43703556
  Scope: machine
ManifestType: installer
ManifestVersion: 1.0.0
