PackageIdentifier: Microsoft.AzureCLI
PackageVersion: 2.29.0
PackageName: Microsoft Azure CLI
Publisher: Microsoft Corporation
Moniker: azure-cli
PackageUrl: https://docs.microsoft.com/en-us/cli/azure/
License: Copyright (C) Microsoft Corporation
ShortDescription: The Azure command-line interface (Azure CLI) is a set of commands used to create and manage Azure resources. The Azure CLI is available across Azure services and is designed to get you working quickly with Azure, with an emphasis on automation.
Installers:
- Architecture: x64
  InstallerUrl: https://azcliprod.azureedge.net/msi/azure-cli-2.29.0.msi
  InstallerType: msi
  InstallerSha256: e76cefe6b9d3484622d26d85d4d35bc2b10e7fbb29492e48d2cea667024d204f
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
