PackageIdentifier: Microsoft.TeamMate
PackageVersion: 0.1.1.0
PackageName: TeamMate
Publisher: https://github.com/microsoft/teammate
License: Copyright (c) Microsoft Corporation
Moniker: teammate
Tags:
- teammate
- azuredevops
- ado
ShortDescription: TeamMate is an application for managing Azure Dev Ops (ADO) work items and pull requests.
PackageUrl: https://github.com/microsoft/TeamMate
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/microsoft/TeamMate/releases/download/0.1.1-ci.111%2BBranch.main.Sha.610914adb6897c1dea5ecd33af94e71c29b39a33/Microsoft.Tools.TeamMate.Production.msi
  InstallerSha256: 7460b831813f822b956c59971b6716b4e1c726cdb2affd61879587c684c79598
  InstallerType: msi
  ProductCode: "{4AAB9873-67F0-4C68-8655-2E0B20C91E8B}"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
