# Automatically updated by the winget bot at 2022/Jan/15
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Huawei.Welink
PackageVersion: 7.13.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://obs-client.obs.cn-north-1.myhuaweicloud.com/WeLink_setup.exe
  InstallerSha256: F236BCCF58D3530C5E3100B1DA68F1FBD53870E25C1C16EEC05854A25C66A306
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
