# Automatically updated by the winget bot at 2022/Jan/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ksnip.ksnip.Continuous
PackageVersion: 1.10.0
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
UpgradeBehavior: install
FileExtensions:
- bmp
- gif
- jpg
- png
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ksnip/ksnip/releases/download/continuous/ksnip-1.10.0-continuous.msi
  InstallerSha256: F9157EE565A870C821BE42C85FE871111D49587E556A3E4404983255C339306E
  ProductCode: '{CAE89A47-E194-4F11-B929-0A12EF63E618}'
ManifestType: installer
ManifestVersion: 1.1.0
