# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: GrafanaLabs.GrafanaOSS
PackageVersion: 8.2.1.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: "{BDDE6CDA-C6A2-46CF-B624-C97272C4F13A}"
Installers:
- Architecture: x64
  InstallerUrl: https://dl.grafana.com/oss/release/grafana-8.2.1.windows-amd64.msi
  InstallerSha256: 09E80BC815A0F7F8D0E916847FEBB8D35B7E4424AA9CCAC7DAC05A87D7178B13
ManifestType: installer
ManifestVersion: 1.0.0

