# Automatically updated by the winget bot at 2022/Jan/05
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Grammarly.ForWindows
PackageVersion: 1.0.2.112
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallerSwitches:
  Silent: /fastforallmode /silent
  SilentWithProgress: /fastforallmode /silent
Installers:
- Architecture: x86
  InstallerUrl: https://download-windows.grammarly.com/GrammarlyInstaller.exe
  InstallerSha256: FE3755E361A5F82B5ADEA4B6AB3F648CF04C4936068519B9B189983D26E53469
  ProductCode: Grammarly Desktop Integrations
ManifestType: installer
ManifestVersion: 1.1.0
