# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Microsoft.OpenJDK.11
PackageVersion: 11.0.13.8
PackageLocale: en-US
Publisher: Microsoft
Author: Microsoft
PackageName: Microsoft Build of OpenJDK with Hotspot 11
PackageUrl: https://www.microsoft.com/openjdk
License: GPL2 with Classpath Exception.
LicenseUrl: https://openjdk.java.net/legal/gplv2+ce.html
ShortDescription: The Microsoft Build of OpenJDK is a new no-cost long-term supported distribution and Microsoft"s new way to collaborate and contribute to the Java ecosystem.
Moniker: ms-openjdk-11
Tags:
- Java
- OpenJDK
- 11
ManifestType: defaultLocale
ManifestVersion: 1.0.0

