# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Microsoft.WindowsAdminCenter
PackageName: Windows Admin Center
Moniker: WAC
PackageVersion: 1.3.44065.0
Publisher: Microsoft Corporation
Author: Microsoft
License: © Microsoft 2020
LicenseUrl: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
MinimumOSVersion: 10.0.0.0
PackageUrl: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-admin-center
Tags:
- Admin Center
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/1/0/5/1059800B-F375-451C-B37E-758FFC7C8C8B/WindowsAdminCenter2110.msi
  InstallerSha256: 5EC8842147FF2CFCEE8638CF69165410F0D275F7859D115992AFED75E873F9B7
  InstallerSwitches:
    Silent: /qn SME_PORT=6516 SSL_CERTIFICATE_OPTION=generate
    SilentWithProgress: /passive SME_PORT=6516 SSL_CERTIFICATE_OPTION=generate
ShortDescription: Microsoft.WindowsAdminCenter
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

