# Created using YamlCreate.ps1 v1.1.7
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: youxiao.yxfile
PackageVersion: 2.1.9.18
DefaultLocale: zh-CN
ManifestType: version
ManifestVersion: 1.0.0

