# Created using YamlCreate.ps1 v1.1.7
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: youxiao.yxfile
PackageVersion: 2.1.9.18
PackageLocale: zh-CN
Publisher: 优效软件
PublisherUrl: https://www.youxiao.cn/yxfile/
#PublisherSupportUrl: 
#PrivacyUrl: 
Author: 优效软件
PackageName: 优效文件助手
PackageUrl: https://www.youxiao.cn/yxfile/
License: 专有软件
#LicenseUrl: 
Copyright: Copyright (C) 2021 www.youxiao.cn
#CopyrightUrl: 
ShortDescription: 助你轻松掌控电脑文件
Description: 优效文件助手是一款为文件标签管理而生的软件，内置了强大的本地文件搜索引擎，助你轻松掌控电脑文件。
Tags:
- 优效
- youxiao
- 文件
- 程序
- 应用
- 标签
- 管理
- 搜索
ManifestType: defaultLocale
ManifestVersion: 1.0.0

