# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.4.9.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- aws
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.4.9.msi
  InstallerSha256: BE45FA449D6DF5FB85919D472FE32E0A1E9B87A7AAFC63A6A08860CAFFF487CD
  ProductCode: '{A7FEB1BB-86D9-43BB-92D9-E38C576EE93B}'
ManifestType: installer
ManifestVersion: 1.1.0
