# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Jackett.Jackett
PackageVersion: 0.18.1001.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/Jackett/Jackett/releases/download/v0.18.1001/Jackett.Installer.Windows.exe
  InstallerSha256: 35479930E759EFCEF36835FBFE12C2792AD8318610E775A4FC9ED12077F8A782
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

