# Automatically updated by the winget bot at 2021/Oct/06
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Honeygain.Honeygain
PackageVersion: 0.10.7.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://download.honeygain.com/windows-app/Honeygain_install.exe
  InstallerSha256: 3DD8C3A3B1689841C9BCC29091261EC39066453EB2EDD5296CB27CB6744593F8
  InstallerSwitches:
    Silent: /q
    SilentWithProgress: /qb
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
