# Automatically updated by the winget bot at 2022/Jan/13
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Logitech.GHUB
PackageVersion: 2022.1.3492
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: neutral
  InstallerUrl: https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
  InstallerSha256: 9F8CB016856C9576AB2A1BFB2AD32E8C2E3F11AA8B3C001471137DD4B6803A86
ManifestType: installer
ManifestVersion: 1.1.0
