# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Anaconda.Anaconda3
PackageVersion: "2021.11"
PackageLocale: en-US
Publisher: Anaconda, Inc.
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: Anaconda3
PackageUrl: https://www.anaconda.com/products/individual
License: BSD 3-Clause License
LicenseUrl: https://docs.conda.io/en/latest/license.html
# Copyright: 
# CopyrightUrl: 
ShortDescription: Anaconda Individual Edition is the easiest way to perform Python/R data science and machine learning on a single machine. Developed for solo practitioners, it is the toolkit that equips you to work with thousands of open-source packages and libraries.
# Description: 
Tags:
- python
- conda
ManifestType: defaultLocale
ManifestVersion: 1.0.0
