# Automatically updated by the winget bot at 2022/Jan/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Keeper.KeeperDesktop
PackageVersion: 16.3.4.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msix
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
PackageFamilyName: KeeperSecurityInc.KeeperPasswordManager_26bb6b95qhpkr
Installers:
- Architecture: x86
  InstallerUrl: https://www.keepersecurity.com/desktop_electron/packages/KeeperPasswordManager.msixbundle
  InstallerSha256: 95AC12528A227BCB1C94CD98AB72E66D5153F6DADB76EBD598C815F7B3C29611
  SignatureSha256: 3D5C7C12F21BF11CF4F64CD90406FB77DBD9CD76E30965207EC86E1155B1386B
- Architecture: x64
  InstallerUrl: https://www.keepersecurity.com/desktop_electron/packages/KeeperPasswordManager.msixbundle
  InstallerSha256: 95AC12528A227BCB1C94CD98AB72E66D5153F6DADB76EBD598C815F7B3C29611
  SignatureSha256: 3D5C7C12F21BF11CF4F64CD90406FB77DBD9CD76E30965207EC86E1155B1386B
ManifestType: installer
ManifestVersion: 1.0.0
