# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: AviSynth.AviSynthPlus
PackageVersion: 3.7.1.3593
PackageLocale: en-US
Publisher: The Public
PublisherUrl: https://github.com/AviSynth/AviSynthPlus
PublisherSupportUrl: https://github.com/AviSynth/AviSynthPlus/issues
# PrivacyUrl: 
Author: qyot27
PackageName: AviSynth+
PackageUrl: https://github.com/AviSynth/AviSynthPlus
License: GPLv2
# LicenseUrl: 
# Copyright: 
# CopyrightUrl: 
ShortDescription: An improved version of the AviSynth frameserver, with improved features and developer friendliness.
# Description: 
# Moniker: 
Tags:
- avs
- avs+
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
