# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: OpenRPAApS.OpenRPA
PackageVersion: 1.2.76.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{21B2A5C0-11A5-4D97-A0D7-EC139D7C96F9}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/open-rpa/openrpa/releases/download/1.2.76/OpenRPA.msi
  InstallerSha256: 78A3D2EFA871F429F704B374A882D9A4505FB873EA2D550E28202C9CE0D60455
ManifestType: installer
ManifestVersion: 1.0.0
