# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: DuongDieuPhap.ImageGlass
PackageVersion: 8.4.2.22
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- ai
- avif
- b64
- bmp
- bvif
- cur
- cut
- dib
- emf
- eps
- exif
- exr
- gif
- hdr
- heic
- heif
- ico
- jfif
- jp2
- jpe
- jpeg
- jpg
- mpg
- pbm
- pcx
- pgm
- png
- ppm
- psd
- raw
- rga
- svg
- tif
- tiff
- webp
- wmf
- wpg
- xbm
- xpm
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/d2phap/ImageGlass/releases/download/8.4.2.22/ImageGlass_8.4.2.22_x64.msi
  InstallerSha256: 08613C1A2A92CAF6DD2CCD7F199112DDBAD3AFA2111FAE58A4A25C14C9A694B8
  ProductCode: '{A5F09BA9-6FE7-4906-B312-1DC9B85C3DEA}'
- Architecture: x86
  InstallerUrl: https://github.com/d2phap/ImageGlass/releases/download/8.4.2.22/ImageGlass_8.4.2.22_x86.msi
  InstallerSha256: 6F231AEB0B7806652445C013D2F34B9656A2FA1D3FADBB1A55E38D1F1C99BE03
  ProductCode: '{F5B8A7F3-13DD-4126-9882-BD8A2C0A708B}'
ManifestType: installer
ManifestVersion: 1.1.0
