# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: ICBC.ICBCChromeExtension
PackageVersion: 1.2.0.0
PackageLocale: en-US
Publisher: ICBC
PackageName: ICBCChromeExtension
License: copyright (c) ICBC
ShortDescription: ICBC Chrome Extension
ManifestType: defaultLocale
ManifestVersion: 1.0.0

