# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: ICBC.ICBCChromeExtension
PackageVersion: 1.2.0.0
Installers:
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://epass.icbc.com.cn/ICBCChromeExtension.msi
  InstallerSha256: 844938344BFD1968FEE35552196231FA8C874A9943982C135A694C033EDA896B
  ProductCode: '{9B537D38-763F-4AA6-BA32-18813119204F}'
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://epass.icbc.com.cn/ICBCChromeExtension.msi
  InstallerSha256: 844938344BFD1968FEE35552196231FA8C874A9943982C135A694C033EDA896B
  ProductCode: '{E387C944-1FAF-4205-A4CC-0066F9D5D698}'
ManifestType: installer
ManifestVersion: 1.0.0

