# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: OpenRPAApS.OpenRPA
PackageVersion: 1.3.45.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/open-rpa/openrpa/releases/download/1.3.45/OpenRPA.msi
  InstallerSha256: F65519F8A38BCDF1A1E360731971B04AF0722ECB112CF452031FF39B898100F6
  ProductCode: '{21FA367D-18D2-4B7E-9D1E-4D6AC55E99A8}'
ManifestType: installer
ManifestVersion: 1.1.0
