# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome.Beta
PackageVersion: 98.0.4758.66
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 599FBC4B3625068E0A92AF16A78CE5C6259A3080593448585FCC4D23A94CBF7A
  ProductCode: '{AA95EDFE-3D7F-337B-BDD2-0E3C44A22C2C}'
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 6A6DA29EAA552C1FD3A9774F73674EACC604519DB31D6CE27F6CB1BDD8E54DF2
  ProductCode: '{5E82507D-3106-32A1-BBA4-FE7DAC3C15BE}'
ManifestType: installer
ManifestVersion: 1.1.0
