# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: GitHub.cli
PackageVersion: 2.1.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- gh
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.1.0/gh_2.1.0_windows_amd64.msi
  InstallerSha256: 1333A7DAE999500EDF7DFC853FC6F0FF4AB60CD6145FCEFA749635772FE4CED5
  UpgradeBehavior: install
  ProductCode: '{7B2B5232-3377-484A-BF8F-CE09AAEEF48E}'
ManifestType: installer
ManifestVersion: 1.0.0

