# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.5-1-19041-1237
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Ability.AbilityOffice.10.Professional
PackageVersion: 10.0.3
PackageLocale: en-US
Publisher: Ability Software International
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: Ability Office 10 Professional
# PackageUrl: 
License: (c) Ability Software International
# LicenseUrl: 
# Copyright: 
# CopyrightUrl: 
ShortDescription: Ability Office 10 Professional complete office suite
# Description: 
# Moniker: 
# Tags: 
ManifestType: defaultLocale
ManifestVersion: 1.0.0
