# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.Kate
PackageVersion: 21.12.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/1542/artifact/kate-21.12.1-1542-windows-msvc2019_64-cl.exe
  InstallerSha256: DF7C2F68FC4A517763D957CF98983EC65AFCF49C7DF23CE250E4CE6CBF68BA26
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/1542/artifact/kate-21.12.1-1542-windows-msvc2019_64-cl.exe
  InstallerSha256: DF7C2F68FC4A517763D957CF98983EC65AFCF49C7DF23CE250E4CE6CBF68BA26
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0
