# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: GitHub.cli
PackageVersion: 2.2.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- gh
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.2.0/gh_2.2.0_windows_amd64.msi
  InstallerSha256: 4A0D7B0C90B0A82A7C41BCCC28CA6C8AF8B94B6027A00781902349DA420B4F82
  UpgradeBehavior: install
  ProductCode: '{FFC8847D-596C-4736-9CB3-36882120D768}'
ManifestType: installer
ManifestVersion: 1.0.0

