# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.5-1-19041-1237
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Ability.AbilityOffice.8.Professional
PackageVersion: 8.0.4
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
ProductCode: '{54DD2B4A-4F4D-4BBC-AC5B-6164A230B844}'
Installers:
- Architecture: x86
  InstallerUrl: https://ability.com/ab8/msi/AbilityPRO8_EN.msi
  InstallerSha256: B8A69346917246E834B023AC29DD75BAD986BDE9341AF95A3EACDE6F5C45687C
  Scope: machine
ManifestType: installer
ManifestVersion: 1.0.0
