# Automatically updated by the winget bot at 2022/Jan/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: WorksMobile.NAVERWORKS
PackageVersion: 3.3.1.11
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Platform:
  - Windows.Desktop
  InstallerLocale: ko-KR
  Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://download.worksmobile.com/k/wminst/r/naverworks/deploy_pcmsgapp_win32_exe
  InstallerSha256: 0379B248D91509BCCFE5C4038F6508D4FF3F719394208C3566C3BD35F1007637
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
