# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Mojang.MinecraftLauncher
PackageVersion: 2.0.0.0
PackageLocale: en-US
Publisher: Mojang
# PublisherUrl: https://www.minecraft.net/en-us
# PublisherSupportUrl: https://help.minecraft.net/hc/en-us
PrivacyUrl: https://privacy.microsoft.com/en-us/privacystatement
Author: Mojang Studios
PackageName: Minecraft Launcher
# PackageUrl: https://www.minecraft.net/en-us
License: Proprietary
# LicenseUrl: https://www.minecraft.net/en-us/terms
Copyright: Mojang (c) 2009-2021
# CopyrightUrl: https://www.minecraft.net/en-us/terms
ShortDescription: Official launcher for Minecraft, a sandbox voxel game
Description: Explore your own unique world, survive the night, and create anything you can imagine!
Moniker: minecraft
Tags:
- game
- minecraft
- minecraft-java
- mojang
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
