# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: schemacrawler.schemacrawler
PackageVersion: 16.15.8
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/schemacrawler/SchemaCrawler-Installers/releases/download/v16.15.8/SchemaCrawler-16.15.8.msi
  InstallerSha256: B8887959A2B7B9176291DB1E407BC4635580123A2304D8009E55AA67BE7846C2
  ProductCode: "{272073B6-84DA-3FB3-91AE-9A04A548261F}"
ManifestType: installer
ManifestVersion: 1.0.0
