# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Microsoft.AccessibilityInsights.Windows.Canary
PackageVersion: 1.1.1769.01
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{953643FD-478C-4186-99D9-506C47638BAC}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/accessibility-insights-windows/releases/download/v1.1.1769.01/AccessibilityInsights.msi
  InstallerSha256: ABCF4C9416D49BC7C2973427672E94C9EBF48D2F05D5EC164D52A154D938B2D8
ManifestType: installer
ManifestVersion: 1.0.0
