# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Jackett.Jackett
PackageVersion: 0.18.940.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Jackett/Jackett/releases/download/v0.18.940/Jackett.Installer.Windows.exe
  InstallerSha256: 450023E3FBD08A0D00F548F0C7C60B29195AC9630D3D83F3E16F71D6FBE4DD5F
ManifestType: installer
ManifestVersion: 1.0.0
