# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: OpenJS.NodeJS
PackageVersion: 16.11.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v16.11.1/node-v16.11.1-x64.msi
  InstallerSha256: F712BD1995C2F6B81450433554AE726C0FFA14B5DBBCEF8C3462A0B58AC52FE8
  UpgradeBehavior: install
  ProductCode: '{2570A423-AF43-4B9C-943D-7F80E484A4F4}'
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v16.11.1/node-v16.11.1-x86.msi
  InstallerSha256: F4C40C7B235FEEFC59D3FEDA691035A2F62BD9D6989185ABB8AACB6E23D955BB
  UpgradeBehavior: install
  ProductCode: '{D7D88BCA-9E10-4AF6-92E1-60CC1EB679EB}'
ManifestType: installer
ManifestVersion: 1.0.0

