# Automatically updated by the winget bot at 2022/Jan/15
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: WhatsApp.WhatsApp.Beta
PackageVersion: 2.2201.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://web.whatsapp.com/desktop-beta/windows/release/x64/WhatsAppSetup-beta.exe
  InstallerSha256: BE1E9279199B26B9C7875C9CDCE99703545DC2561815A461D4CFFA58F7190E54
- Architecture: x86
  InstallerUrl: https://web.whatsapp.com/desktop-beta/windows/release/ia32/WhatsAppSetup-beta.exe
  InstallerSha256: C89705B49FE54D3302FFA9197EF9B44325ED184AF0DD3E5542E2A40A4C01C450
ManifestType: installer
ManifestVersion: 1.1.0
