# Automatically updated by the winget bot at 2022/Jan/19
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Oracle.JDK.17
PackageVersion: 17.0.2.0
PackageLocale: en-US
Publisher: Oracle Corporation
PackageName: Java SE Development Kit 17
License: Copyright (c) Oracle
ShortDescription: The JDK is a development environment for building applications and components using the Java programming language.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
