# Created with YamlCreate.ps1 v2.0.0 $debug=AUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: VB-Audio.Voicemeeter.Potato
PackageVersion: 3.0.2.1
Platform:
- Windows.Desktop
MinimumOSVersion: 5.1.2600.2180
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -install
  SilentWithProgress: -install
  Upgrade: -upgrade
UpgradeBehavior: install
Protocols:
- vban
Installers:
- Architecture: x64
  InstallerUrl: https://download.vb-audio.com/Download_CABLE/Voicemeeter8Setup.exe
  InstallerSha256: FFF4082EC9CBE38AAB78C03CFDF9172B766386CEC4024DF4F3A7A81D9A1D629A
- Architecture: x86
  InstallerUrl: https://download.vb-audio.com/Download_CABLE/Voicemeeter8Setup.exe
  InstallerSha256: FFF4082EC9CBE38AAB78C03CFDF9172B766386CEC4024DF4F3A7A81D9A1D629A
ManifestType: installer
ManifestVersion: 1.0.0
