# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Cisco.CiscoWebexMeetings
PackageVersion: 41.10.4.4
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://akamaicdn.webex.com/client/WBXclient-41.10.4-4/webexapp.msi
  InstallerSha256: E5107EB28E5713D55F04B590C01D2BA82C8FF3472404F5567053D39E853B56A6
  UpgradeBehavior: install
  ProductCode: '{57C88506-7CD7-255B-FC2A-D6A5B0E5F006}'
ManifestType: installer
ManifestVersion: 1.0.0

