# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Streamlabs.StreamlabsOBS
PackageVersion: 1.5.2
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://slobs-cdn.streamlabs.com/Streamlabs+OBS+Setup+1.5.2.exe
  InstallerSha256: F8D0B8BDDC28236B7DAF47D03790CA786E94016CCFE23FC7609E8CA73E9866B5
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

