# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.4.1.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- aws
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.4.1.msi
  InstallerSha256: 2AB746DBE939823A6568245488070D696CCBB6CDAAFDFA2BEA15DE53138B9AE7
  ProductCode: '{E555F614-9478-48BA-9CE9-6B5EDE23FC3C}'
ManifestType: installer
ManifestVersion: 1.1.0
