# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Spotify.Spotify
PackageVersion: 1.1.76.447.g11f432d8
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
