# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Giuspen.Cherrytree
PackageVersion: 0.99.43.0
PackageLocale: en-US
Publisher: Giuseppe Penone
PublisherUrl: https://www.giuspen.com
PublisherSupportUrl: https://github.com/giuspen/cherrytree/issues
# PrivacyUrl: 
Author: Giuseppe Penone
PackageName: CherryTree
PackageUrl: https://www.giuspen.com/cherrytree
License: GPLv3
LicenseUrl: https://github.com/giuspen/cherrytree/blob/master/license.txt
# Copyright: 
CopyrightUrl: https://github.com/giuspen/cherrytree/blob/master/license.txt
ShortDescription: A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single xml or sqlite file.
# Description: 
# Moniker: 
Tags:
- note
- wiki
- editor
ManifestType: defaultLocale
ManifestVersion: 1.0.0
