# Created using YamlCreate.ps1 v1.1.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: InfiniteRed.Reactotron
PackageVersion: 2.17.1.713
MinimumOSVersion: 10.0.0.0
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/infinitered/reactotron/releases/download/v2.17.1/Reactotron.2.17.1.msi
  InstallerSha256: F8292498B15B81D236AB6983857960F228325CF3FB682A0F670B496C31117FD3
  ProductCode: '{2139D21F-F924-4BC4-9291-099F33653BBA}'
- Architecture: x64
  InstallerType: nullsoft # electron-builder
  Scope: user
  InstallerUrl: https://github.com/infinitered/reactotron/releases/download/v2.17.1/Reactotron.Setup.2.17.1.exe
  InstallerSha256: 076F8424B8BD02EDB8E01B3AFEC23D835A779C6A93048CF5B3A257E794863659
  InstallerSwitches:
    Upgrade: --updated
  ProductCode: '{b4f20791-aeac-535e-ab41-2e527d2fc694}'
ManifestType: installer
ManifestVersion: 1.0.0

