# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: OpenMedia.4KYoutubetoMP3
PackageVersion: 4.3.5.4610
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

