# Automatically updated by the winget bot at 2022/Jan/12
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Nlitesoft.NTLite
PackageVersion: 2.3.3.8567
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.ntlite.com/files/NTLite_setup_x64.exe
  InstallerSha256: 60BC7854D4922DF8B4B9B1709ACB692BC98AB2A4326BDEBC5FBA25005CD70584
- Architecture: x86
  InstallerUrl: https://downloads.ntlite.com/files/NTLite_setup_x86.exe
  InstallerSha256: 840ABDFBCEA9F0F779E30FBB65D2482E0EC875CC6428A1241C449B41FBA9287A
ManifestType: installer
ManifestVersion: 1.1.0
