# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: DoltHub.Dolt
PackageVersion: 0.30.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{8C709A9E-987C-4D9F-9878-942FB4F4EEF0}'
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/dolthub/dolt/releases/download/v0.30.2/dolt-windows-amd64.msi
  InstallerSha256: 7D4D8CC346B77006CD12EC9B286C222035503E2683A770E4C6443248902FC11A
  ProductCode: '{CC423F65-534D-4B85-8BAF-3B0BA832A6B0}'
ManifestType: installer
ManifestVersion: 1.0.0

