# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: OpenJS.NodeJS.Nightly
PackageVersion: 17.0.0-20211013
PackageLocale: en-US
Publisher: Node.js Foundation
PackageName: Node.js Nightly
PackageUrl: https://nodejs.org/en/
License: (c) 2021 Node.js Foundation. All rights reserved.
LicenseUrl: https://raw.githubusercontent.com/nodejs/node/master/LICENSE
ShortDescription: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine.
Moniker: nodejs-nightly
ManifestType: defaultLocale
ManifestVersion: 1.0.0

